### ISSUE TITLE
Errors when printed through webkit IFRS & Print IFRS options

### ISSUE THREAD

**Issue by moturi12** [Vauxoo/odoo-ifrs#36]
Hi - Below error comes when trying to print through webkit IFRS and Print IFRS option.

File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 718, in _exec_template
callable_(context, _args, *_kwargs)
File "memory:0x7f7e3904e510", line 20, in render_body
<tr><td><div class="td_company">${ ifrs._get_period_print_info(data['period'],data['report_type']) }</div></td></tr>
KeyError: 'period'

**Comment by hbto** [comment]
Oh, Thanks,

I will provide housekeeping for some print actions,
as all reports are actually in webkit.

Best Regards.

**Comment by hbto** [comment]
Dear @moturi12 

webkit IFRS & Print IFRS  options are no longer show in More Menu
besides Print Report option now is only available for only one record
as that is intended to be so.

I will be closing your ticket.

If you think there are remaining issues open this ticket or create a new one.

Best Regards.
