### ISSUE TITLE
[8.0] ifrs_report: ParseError "43" while parsing /root/odoo-ifrs/ifrs_report/demo/demo.xml:388,

### ISSUE THREAD

**Issue by KarenKawaii** [Vauxoo/odoo-ifrs#76]
**module:** `ifrs_report`
**version:** 8.0
**Using t2d and raditz with an up to date yoytec container**

**Steps to reproduce:**
1. Make a t2d for yoytec project.
2. Create a new image and container for yoytec
3. Run the following command as example:

``` bash
[root@bd4b7d5f93ad]~/Vauxoo/yoytec$
 (8.0)$ TEST_ENABLE="0" /entrypoint.sh
```

**Current behaviour:**
An error into an updated container made with t2d and using raditz. 
![odoo-ifrs-error-report](https://cloud.githubusercontent.com/assets/11741384/17828183/684cf412-6650-11e6-816e-4fd9e50a6208.png)

**Expected behaviour**
No error appears. Instead of that a `test_server.py` successful has to appears.

**Context**
Latest yoytec commit:

``` bash
commit 0051d403847ecae2b96bed82ed75818fce1325d4
Author: Hugo Adan [Vauxoo] <hugo@vauxoo.com>
Date:   Wed Aug 17 15:43:06 2016 -0500

    [FIX] lint website_yoytec/models/res_config.py:27: W0621 :redefined-outer-name (#1849)
```

https://github.com/Vauxoo/yoytec/commit/0051d403847ecae2b96bed82ed75818fce1325d4

Latest odoo-ifrs commit:

``` bash
commit 203ad0630cc197a6fc365ff7c91cdb81063f2d40
Author: Humberto Arocha <hbto@vauxoo.com>
Date:   Wed Aug 17 14:32:45 2016 -0400

    [PYLINT]
```

https://github.com/Vauxoo/odoo-ifrs/commit/203ad0630cc197a6fc365ff7c91cdb81063f2d40

**Comment by KarenKawaii** [comment]
Hi @hbto 
Could you check it please?

**Comment by hbto** [comment]
@KarenKawaii try again,
Please

**Comment by KarenKawaii** [comment]
Thanks a lot @hbto 

![odoo-ifrs-corrected](https://cloud.githubusercontent.com/assets/11741384/17873139/6dd0ee58-6889-11e6-81a9-db5b8b3a3890.png)

I will close this issue.

Regards.
