### ISSUE TITLE
When printing Report in HTML Format Footer appears scrambled

### ISSUE THREAD

**Issue by hbto** [Vauxoo/odoo-ifrs#8]
I think that is better to silence it when report is in HTML,
or at least provide only meaningful data and get rid of paging as
it does not make sense but in pdf.

**Comment by nhomar** [comment]
@hbto Which wkhtml version you have installed?

AFAICK, the problem with headers is related to wktohtml version,.

**Comment by hbto** [comment]
wkhtmltopdf 0.12.1 (with patched qt)
when printing with HTML, report keeps footer (paging) which does not make sense 
in HTML format,

It only makes sense in PDF format.

**Comment by hbto** [comment]
This issue has already been fixed.

It no longer applies
